# Site settings
title: Couple, a Jekyll Theme
tag_text: Couple
description: Couple is a Jekyll theme that supports single-page websites only, but supports them well. Yes, it’s responsive.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
